### ISSUE TITLE
test 30-exit.t fails on Windows 10 (Strawberry 5.20.2)

### ISSUE THREAD

**Issue by iamlgh** [book/System-Command#29]
[build.log](https://github.com/book/System-Command/files/4986527/build.log)

I have attached the build log for System-Command-1.121 that shows the 30-exit.t test fails saying:

```
t/30-exit.t .............. Can't find string terminator "'" anywhere before EOF at -e line 1.
t/30-exit.t .............. 1/?
#   Failed test 'exit status not clobbered'
#   at t/30-exit.t line 11.
#          got: '255'
#     expected: '3'
# Looks like you failed 1 test of 1.
t/30-exit.t .............. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
```
The error is with this call:
`perl -Ilib -MSystem::Command -e '
    my \$out = System::Command->new(qw($^X -e1))->stdout;
    exit 3;
'`;

I changed to use double quotes, and the test passes (t/30-exit.t .............. ok). Windows needs double quotes (") to work, not single quotes.

**Comment by iamlgh** [comment]
I opened the same problem in RT, [https://rt.cpan.org/Public/Bug/Display.html?id=133230], because I noticed that metacpan linked to RT and not github. the bug in RT also has the fixed test attached.

**Comment by book** [comment]
Thanks for making the effort of sending your report to both systems. I've finally applied your patch, and it will be in the next release.

**Comment by book** [comment]
Applied as 87c89a37e471b9e500cb27e57104890d9019a242.
