### ISSUE TITLE
Test modules in BuildRequires

### ISSUE THREAD

**Issue by oalders** [book/System-Command#30]
Is there any reason this can't be (re)moved?

```
[Prereqs / BuildRequires]
Test::CPAN::Meta =
Test::Pod =
Test::Pod::Coverage =
Pod::Coverage::TrustPod =
```

Ideally these would be development requirements and would only be run as author tests. I was just looking at a build log for Windows that is failing and I was surprised to see these modules being installed as part of the build process.

**Comment by book** [comment]
Good point. I'll have a look.

**Comment by book** [comment]
Applied as f4d6ea109c94ef8811cf843e1199f50911d6cf70.

**Comment by book** [comment]
Applied as f4d6ea109c94ef8811cf843e1199f50911d6cf70.
